pub const TOOL_NAMES: [&str; 15] = [
    "agent_run",
    "agent_list",
    "agent_get",
    "agent_capture",
    "agent_delete",
    "agent_label",
    "mail_send",
    "mail_read",
    "mail_check",
    "mail_stop_check",
    "nudge",
    "link",
    "logs",
    "wait",
    "doctor",
];
