// AUTO-GENERATED by build.rs from tools/*.toml - do not edit
#![allow(clippy::all)]

#[rustfmt::skip]
pub fn generated_tool_list() -> serde_json::Value {
    let tools: Vec<serde_json::Value> = vec![
        generated_tool_schema(include_str!("generated_schema/session_run.json"), "session_run"),
        generated_tool_schema(include_str!("generated_schema/agent_run.json"), "agent_run"),
        generated_tool_schema(include_str!("generated_schema/session_list.json"), "session_list"),
        generated_tool_schema(include_str!("generated_schema/agent_list.json"), "agent_list"),
        generated_tool_schema(include_str!("generated_schema/session_get.json"), "session_get"),
        generated_tool_schema(include_str!("generated_schema/agent_get.json"), "agent_get"),
        generated_tool_schema(include_str!("generated_schema/namespace_list.json"), "namespace_list"),
        generated_tool_schema(include_str!("generated_schema/namespace_get.json"), "namespace_get"),
        generated_tool_schema(include_str!("generated_schema/session_capture.json"), "session_capture"),
        generated_tool_schema(include_str!("generated_schema/agent_capture.json"), "agent_capture"),
        generated_tool_schema(include_str!("generated_schema/session_delete.json"), "session_delete"),
        generated_tool_schema(include_str!("generated_schema/agent_delete.json"), "agent_delete"),
        generated_tool_schema(include_str!("generated_schema/session_label.json"), "session_label"),
        generated_tool_schema(include_str!("generated_schema/agent_label.json"), "agent_label"),
        generated_tool_schema(include_str!("generated_schema/mail_send.json"), "mail_send"),
        generated_tool_schema(include_str!("generated_schema/mail_read.json"), "mail_read"),
        generated_tool_schema(include_str!("generated_schema/mail_check.json"), "mail_check"),
        generated_tool_schema(include_str!("generated_schema/mail_stop_check.json"), "mail_stop_check"),
        generated_tool_schema(include_str!("generated_schema/nudge.json"), "nudge"),
        generated_tool_schema(include_str!("generated_schema/logs.json"), "logs"),
        generated_tool_schema(include_str!("generated_schema/wait.json"), "wait"),
        generated_tool_schema(include_str!("generated_schema/doctor.json"), "doctor"),
    ];
    serde_json::json!({ "tools": tools })
}

fn generated_tool_schema(json: &str, name: &str) -> serde_json::Value {
    serde_json::from_str(json).unwrap_or_else(|error| {
        panic!("generated schema for {name} is valid JSON: {error}");
    })
}
