// AUTO-GENERATED by build.rs from tools.toml - do not edit
#![allow(clippy::all)]

pub fn generated_tool_list() -> serde_json::Value {
    let tools: Vec<serde_json::Value> = vec![
        serde_json::from_str(include_str!("generated_schema/agent_run.json"))
            .expect("generated schema for agent_run is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/agent_list.json"))
            .expect("generated schema for agent_list is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/agent_get.json"))
            .expect("generated schema for agent_get is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/agent_delete.json"))
            .expect("generated schema for agent_delete is valid JSON"),
    ];
    serde_json::json!({ "tools": tools })
}
