// AUTO-GENERATED by build.rs from tools.toml - do not edit
#![allow(clippy::all)]

pub fn generated_tool_list() -> serde_json::Value {
    let tools: Vec<serde_json::Value> = vec![
        serde_json::from_str(include_str!("generated_schema/agent_run.json"))
            .expect("generated schema for agent_run is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/agent_list.json"))
            .expect("generated schema for agent_list is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/agent_get.json"))
            .expect("generated schema for agent_get is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/agent_delete.json"))
            .expect("generated schema for agent_delete is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/agent_label.json"))
            .expect("generated schema for agent_label is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/mail_send.json"))
            .expect("generated schema for mail_send is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/mail_read.json"))
            .expect("generated schema for mail_read is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/mail_check.json"))
            .expect("generated schema for mail_check is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/mail_stop_check.json"))
            .expect("generated schema for mail_stop_check is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/nudge.json"))
            .expect("generated schema for nudge is valid JSON"),
    ];
    serde_json::json!({ "tools": tools })
}
