#![allow(dead_code)]

use std::fs;
use std::path::{Path, PathBuf};

const TOOL_SOURCE_ORDER: &[&str] = &[
    "run", "session", "capture", "label", "mail", "nudge", "logs", "wait", "doctor",
];

pub fn ordered_tool_source_paths(tools_dir: &Path) -> Result<Vec<PathBuf>, String> {
    let mut paths = fs::read_dir(tools_dir)
        .map_err(|error| format!("failed to read {}: {error}", tools_dir.display()))?
        .map(|entry| {
            entry
                .map(|entry| entry.path())
                .map_err(|error| format!("failed to read tool source entry: {error}"))
        })
        .collect::<Result<Vec<_>, _>>()?;
    paths.retain(|path| path.extension().and_then(|ext| ext.to_str()) == Some("toml"));
    paths.sort_by_key(|left| tool_source_sort_key(left));
    Ok(paths)
}

pub fn read_tool_sources(paths: &[PathBuf]) -> Result<String, String> {
    let mut content = String::new();
    for path in paths {
        let source = fs::read_to_string(path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        content.push_str(&source);
        if !content.ends_with('\n') {
            content.push('\n');
        }
        content.push('\n');
    }
    Ok(content)
}

pub fn render_tool_source_includes(repo_root: &Path, paths: &[PathBuf]) -> Result<String, String> {
    let mut lines = vec![
        "// AUTO-GENERATED by build.rs from tools/*.toml - do not edit".to_string(),
        "pub const TOOL_SOURCE_FILES: &[(&str, &str)] = &[".to_string(),
    ];
    for path in paths {
        let name = path
            .strip_prefix(repo_root)
            .map_err(|error| {
                format!(
                    "failed to strip repo root {} from {}: {error}",
                    repo_root.display(),
                    path.display()
                )
            })?
            .to_string_lossy()
            .replace('\\', "/");
        let include_path = path
            .canonicalize()
            .map_err(|error| format!("failed to canonicalize {}: {error}", path.display()))?
            .to_string_lossy()
            .to_string();
        lines.push(format!(
            "    (\"{}\", include_str!(\"{}\")),",
            rust_escape(&name),
            rust_escape(&include_path)
        ));
    }
    lines.push("];".to_string());
    lines.push(String::new());
    Ok(lines.join("\n"))
}

fn tool_source_sort_key(path: &Path) -> (usize, String) {
    let stem = path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("");
    let index = TOOL_SOURCE_ORDER
        .iter()
        .position(|known| *known == stem)
        .unwrap_or(TOOL_SOURCE_ORDER.len());
    (index, stem.to_string())
}

fn rust_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
