use std::collections::HashSet;
use std::fs;
use std::path::Path;

#[path = "src/tool_contracts.rs"]
mod tool_contracts;
#[path = "src/tool_docs.rs"]
mod tool_docs;
#[path = "src/tool_examples.rs"]
mod tool_examples;

use tool_contracts::{ToolContract, ToolContractRegistry};
use tool_docs::{
    render_generated_instructions_rs, render_readme_md, render_server_instructions, render_skill_md,
};

fn main() {
    println!("cargo:rerun-if-changed=../../tools.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/tool_contracts.rs");
    println!("cargo:rerun-if-changed=src/tool_docs.rs");
    println!("cargo:rerun-if-changed=src/tool_examples.rs");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set");
    let tools_path = Path::new(&manifest_dir).join("../../tools.toml");
    let content = fs::read_to_string(&tools_path).expect("tools.toml is readable");
    let registry = ToolContractRegistry::from_toml_str(&content).expect("tools.toml parses");

    write_schema_outputs(&manifest_dir, registry.tools());
    write_docs_outputs(&manifest_dir, &registry);
}

fn write_schema_outputs(manifest_dir: &str, tools: &[ToolContract]) {
    let (schema_rs, schema_files) = generate_mcp_schema(tools);
    write_if_changed(
        &Path::new(manifest_dir).join("src/mcp/generated_schema.rs"),
        &schema_rs,
    );

    let schema_dir = Path::new(manifest_dir).join("src/mcp/generated_schema");
    fs::create_dir_all(&schema_dir).expect("generated schema dir can be created");
    let mut expected = HashSet::new();
    for (file_name, content) in &schema_files {
        expected.insert(file_name.as_str());
        write_if_changed(&schema_dir.join(file_name), content);
    }
    remove_stale_generated_files(&schema_dir, &expected);
}

fn write_docs_outputs(manifest_dir: &str, registry: &ToolContractRegistry) {
    let instructions = render_server_instructions(registry.skill(), registry.tools());
    let instructions_rs = render_generated_instructions_rs(&instructions);
    write_if_changed(
        &Path::new(manifest_dir).join("src/mcp/generated_instructions.rs"),
        &instructions_rs,
    );

    write_if_changed(
        &Path::new(manifest_dir).join("src/cli/generated_help.rs"),
        &generate_cli_help(registry.tools()),
    );

    let templates_dir = Path::new(manifest_dir).join("templates");
    fs::create_dir_all(&templates_dir).expect("templates dir can be created");
    write_if_changed(
        &templates_dir.join("SKILL.md"),
        &render_skill_md(registry.skill(), registry.tools()),
    );
    write_if_changed(
        &Path::new(manifest_dir).join("../../README.md"),
        &render_readme_md(registry.skill(), registry.tools()),
    );
}

fn generate_mcp_schema(tools: &[ToolContract]) -> (String, Vec<(String, String)>) {
    let mut include_lines = Vec::new();
    let mut schema_files = Vec::new();
    for tool in tools {
        let file_name = tool.artifacts.mcp_schema_file.clone();
        let tool_entry = tool.tool_entry_value();
        let json = serde_json::to_string_pretty(&tool_entry).expect("tool schema serializes");
        include_lines.push(format!(
            "        serde_json::from_str(include_str!(\"generated_schema/{file_name}\"))\n            .expect(\"generated schema for {} is valid JSON\"),",
            tool.name
        ));
        schema_files.push((file_name, format!("{json}\n")));
    }

    let mut schema_rs = String::new();
    schema_rs.push_str("// AUTO-GENERATED by build.rs from tools.toml - do not edit\n");
    schema_rs.push_str("#![allow(clippy::all)]\n\n");
    schema_rs.push_str("pub fn generated_tool_list() -> serde_json::Value {\n");
    schema_rs.push_str("    let tools: Vec<serde_json::Value> = vec![\n");
    for line in include_lines {
        schema_rs.push_str(&line);
        schema_rs.push('\n');
    }
    schema_rs.push_str("    ];\n");
    schema_rs.push_str("    serde_json::json!({ \"tools\": tools })\n");
    schema_rs.push_str("}\n");
    (schema_rs, schema_files)
}

fn generate_cli_help(tools: &[ToolContract]) -> String {
    let mut lines = vec![
        "// AUTO-GENERATED by build.rs from tools.toml - do not edit".to_string(),
        "#![allow(clippy::all)]".to_string(),
    ];
    for tool in tools {
        let prefix = &tool.artifacts.cli_help_prefix;
        lines.push("#[rustfmt::skip]".to_string());
        lines.push(format!(
            "pub const {prefix}_ABOUT: &str = \"{}\";",
            rust_escape(&tool.cli.about)
        ));
        for param in &tool.params {
            if let Some(help) = &param.cli_help {
                lines.push("#[rustfmt::skip]".to_string());
                lines.push(format!(
                    "pub const {prefix}_{}_HELP: &str = \"{}\";",
                    tool_contracts::rust_const_name(&param.name),
                    rust_escape(help)
                ));
            }
        }
        lines.push(String::new());
    }
    lines.join("\n")
}

fn write_if_changed(path: &Path, content: &str) {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == content
    {
        return;
    }
    fs::write(path, content).unwrap_or_else(|error| {
        panic!("failed to write {}: {error}", path.display());
    });
}

fn remove_stale_generated_files(dir: &Path, expected: &HashSet<&str>) {
    for entry in fs::read_dir(dir).expect("generated schema dir can be read") {
        let path = entry.expect("generated schema entry can be read").path();
        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if path.extension().and_then(|ext| ext.to_str()) == Some("json")
            && !expected.contains(file_name)
        {
            fs::remove_file(&path).unwrap_or_else(|error| {
                panic!("failed to remove {}: {error}", path.display());
            });
        }
    }
}

fn rust_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
