use std::fmt::Write;

use crate::tool_contracts::{
    SharedContent, SkillConfig, ToolContract, render_selector_grammar_block,
};
use crate::tool_examples;

const README_PREAMBLE: &str = r#"<!-- AUTO-GENERATED by crates/sm-cli/build.rs from tools/*.toml. Do not edit generated sections by hand. -->

# session-matters

Control plane for Helioy sessions.

## Runtime

```bash
rtm daemon start
sm daemon start
sm create namespace project-alpha
sm config set-context project-alpha
sm create session claude --role general --dir "$PWD"
sm run claude --role general --dir "$PWD" --detach
sm run codex --role reviewer --namespace project-alpha --target tmux:agents:0.1 --force --detach
sm get session --selector id:<session-id> --show-labels
sm capture <session-id>
sm delete namespace project-alpha
sm logs id:<session-id>
sm doctor
sm daemon stop
rtm daemon stop
```

The daemon uses `~/.sm/sm.pid`, `~/.sm/sock`, and `~/.sm/sm.db` by default.
Set `SM_HOME` to use an alternate runtime directory.
The daemon connects to runtime-matters through `~/.rtm/sock`, or `RTM_SOCKET_PATH`.
`smd` requires `rtmd` with runtime protocol 0.6 or newer.

## Namespaces

Namespaces group sessions under explicit, operator created slugs. The `default`
namespace always exists, and pre migration session rows are backfilled into
`default` on upgrade.

The CLI uses kubectl shaped resource buckets for CRUD: `sm create session`,
`sm get session`, `sm delete session`, `sm create namespace`,
`sm get namespace`, and `sm delete namespace`. The plural `sessions` and
`namespaces` forms remain aliases for reads and session deletes.

`sm create session` is the declarative create-resource surface. It creates a
daemon backed headless session record. `sm run` is the imperative surface for
create and bind target workflows. It accepts the same session identity inputs
plus runtime target controls such as `--target`, `--detach`, and `--force`.
Use `sm run --force` only to preempt an occupied tmux pane. Other spawn
conflicts remain fatal.

### Migration Guide

Create the namespace before running sessions into it:

```bash
sm create namespace project-alpha
sm config set-context project-alpha
```

The user namespace context lives under `SM_HOME`, or `~/.sm` when `SM_HOME` is
unset. CLI selector reads default to that context. If no context is set, the CLI
uses `default`. `--namespace <slug>` overrides user context, and the namespace
must already exist.

Namespace resolution precedence is: explicit `--namespace`, `SM_NAMESPACE`,
user namespace context, then `default`.

`sm run --dir <path>` is the directory flag. New callers should use `--dir` and
`--namespace`.

Selectors support `namespace:<slug>` and `dir:<path>`. `workspace:<path>` selectors
were removed in this migration. Use `dir:<path>` for path based selection or
`namespace:<slug>` for namespace based selection.

Labels are session metadata, not CRUD resources. Use `sm label <SELECTOR>
key=value` to set a label, `sm label <SELECTOR> key-` to remove one, and
`sm get session --show-labels` to include labels in human output. JSON session
output always includes labels.

CLI selector reads default to the resolved namespace when user context or
`--namespace` resolves. This applies to selector consuming surfaces:
`sm get session --selector <SELECTOR>`, `sm mail send --to <SELECTOR>`,
`sm nudge --to <SELECTOR>`, `sm label <SELECTOR> <MUTATION>`,
`sm logs <SELECTOR>`, `sm wait <SELECTOR> --for <CONDITION>`, and
`sm delete session <SELECTOR>`. Use `-A` or `--all-namespaces` to bypass
default scoping where the command offers namespace scope flags.

`sm delete namespace <slug>` terminates sessions in that namespace, deletes the
namespace record, and clears the user context when it points at the deleted
namespace. Namespaces cannot be renamed. Sessions cannot move between
namespaces. Stop the old session and spawn a replacement in the target namespace
when a namespace choice changes.

MCP callers should use `session_*` tools. `agent_*` tools remain deprecated
compatibility aliases during this release. MCP read tools accept `namespace` to
scope reads and `all_namespaces` to bypass scoping. When neither is supplied, the
daemon falls back to the caller session's stored namespace. The daemon does not
walk the MCP server process cwd.

A future hard cut master will remove the compatibility surfaces after the
migration window.

## MCP Server

```bash
sm mcp
```

"#;

const README_FOOTER: &str = r"## Development

```bash
just check
just build
just test
```
";

pub fn render_server_instructions(
    skill: Option<&SkillConfig>,
    shared: &SharedContent,
    tools: &[ToolContract],
) -> String {
    let mut out = String::new();
    out.push_str("session-matters controls local Helioy sessions through smd.\n\n");
    out.push_str("Use session_run to run a session, session_list to inspect sessions, ");
    out.push_str(
        "session_get before acting on one id, and session_delete to terminate a session.\n\n",
    );
    append_tool_bullets(&mut out, tools);
    append_selector_grammar_section(&mut out, shared);
    if let Some(skill) = skill {
        out.push('\n');
        out.push_str(skill.workflow.trim());
    }
    out
}

pub fn render_generated_instructions_rs(instructions: &str) -> String {
    format!(
        "// AUTO-GENERATED by build.rs from tools/*.toml - do not edit\n\
         #![allow(clippy::all)]\n\n\
         pub const SERVER_INSTRUCTIONS: &str = {instructions:?};\n"
    )
}

pub fn render_skill_md(
    skill: Option<&SkillConfig>,
    shared: &SharedContent,
    tools: &[ToolContract],
) -> String {
    let mut out = String::new();
    out.push_str("---\n");
    out.push_str("name: session-matters\n");
    out.push_str("description: Control local Helioy sessions through smd via MCP tools.\n");
    out.push_str("---\n\n");
    out.push_str("# session-matters\n\n");
    out.push_str("Use this skill when you need to run, list, inspect, or terminate local Helioy sessions.\n\n");
    append_tool_table(&mut out, tools);
    append_selector_grammar_section(&mut out, shared);
    append_examples(&mut out);
    if let Some(skill) = skill {
        out.push('\n');
        out.push_str(skill.workflow.trim());
        out.push('\n');
    }
    out
}

pub fn render_readme_md(
    skill: Option<&SkillConfig>,
    shared: &SharedContent,
    tools: &[ToolContract],
) -> String {
    let mut out = String::new();
    out.push_str(README_PREAMBLE);
    append_tool_table(&mut out, tools);
    append_selector_grammar_section(&mut out, shared);
    append_examples(&mut out);
    if let Some(skill) = skill {
        out.push_str("\n## Workflow\n\n");
        out.push_str(skill.workflow.trim());
        out.push('\n');
    }
    out.push_str(README_FOOTER);
    out
}

fn append_tool_bullets(out: &mut String, tools: &[ToolContract]) {
    out.push_str("Tools:\n");
    for tool in tools {
        let _ = writeln!(out, "- {}: {}", tool.name, tool.mcp_description);
    }
}

fn append_tool_table(out: &mut String, tools: &[ToolContract]) {
    out.push_str("## MCP Tools\n\n");
    out.push_str("| Tool | CLI | Purpose |\n");
    out.push_str("|------|-----|---------|\n");
    for tool in tools {
        let _ = writeln!(
            out,
            "| `{}` | `sm {}` | {} |",
            tool.name, tool.cli.name, tool.mcp_description
        );
    }
}

fn append_selector_grammar_section(out: &mut String, shared: &SharedContent) {
    if let Some(grammar) = render_selector_grammar_block(shared) {
        out.push_str("\n## Selector Grammar\n\n");
        out.push_str(&grammar);
        out.push('\n');
    }
}

fn append_examples(out: &mut String) {
    out.push_str("\n## Examples\n\n");
    for example in tool_examples::examples() {
        let rendered = serde_json::to_string_pretty(&example.arguments).unwrap_or_else(|error| {
            panic!("example arguments serialize: {error}");
        });
        let _ = writeln!(
            out,
            "### `{}`\n\n```json\n{}\n```\n",
            example.tool, rendered
        );
    }
}
