use std::fmt::Write;

use crate::tool_contracts::{SkillConfig, ToolContract};
use crate::tool_examples;

const README_PREAMBLE: &str = r#"<!-- AUTO-GENERATED by crates/sm-cli/build.rs from tools.toml. Do not edit generated sections by hand. -->

# session-matters

Control plane for Helioy agent sessions.

## Runtime

```bash
rtm daemon start
sm daemon start
sm init namespace project-alpha
sm run claude --role general --dir "$PWD" --detach
sm run codex --role reviewer --namespace project-alpha --target tmux:agents:0.1 --detach
sm capture --selector id:<session-id>
sm get agents
sm logs id:<session-id>
sm doctor
sm daemon stop
rtm daemon stop
```

The daemon uses `~/.sm/sm.pid`, `~/.sm/sock`, and `~/.sm/sm.db` by default.
Set `SM_HOME` to use an alternate runtime directory.
The daemon connects to runtime-matters through `~/.rtm/sock`, or `RTM_SOCKET_PATH`.
`smd` requires `rtmd` with runtime protocol 0.6 or newer.

## Namespaces

Namespaces group sessions under explicit, operator created slugs. The `default`
namespace always exists, and pre migration session rows are backfilled into
`default` on upgrade.

### Migration Guide

Create the namespace before spawning into it:

```bash
sm create namespace project-alpha
mkdir -p .sm
echo project-alpha > .sm/namespace
```

`sm init namespace project-alpha` performs both steps for the current directory,
or use `--dir <path>` to write the marker elsewhere. The marker is a UTF-8 text
file at `.sm/namespace` containing one namespace slug. CLI marker discovery walks
from the selected directory toward the filesystem root and stops after checking
`$HOME`. If no marker resolves, the CLI uses `default`. `--namespace <slug>`
overrides marker discovery, and the namespace must already exist.

`sm run --dir <path>` is the current directory flag. `--workspace <path>` remains
a deprecated compatibility alias for `--dir` during this release and emits a
warning. New callers should use `--dir` and `--namespace`.

Selectors support `namespace:<slug>` and `dir:<path>`. `workspace:<path>` selectors
were removed in this migration. Use `dir:<path>` for path based selection or
`namespace:<slug>` for namespace based selection.

CLI selector reads default to the resolved namespace when a marker or
`--namespace` resolves. This applies to the selector consuming surfaces in this
release: `sm get agent`, `sm get agents`, `sm mail send --to <selector>`,
`sm nudge --to <selector>`, `sm label`, and `sm delete agent`. Use `-A` or
`--all-namespaces` to bypass default scoping.

MCP callers should use `session_*` tools. `agent_*` tools remain deprecated
compatibility aliases during this release. MCP read tools accept `namespace` to
scope reads and `all_namespaces` to bypass scoping. When neither is supplied, the
daemon falls back to the caller session's stored namespace. The daemon does not
walk the MCP server process cwd.

Design snapshots for the migration live in `NOTES/api-surface-and-entities.md`,
`NOTES/namespace-packaging.md`, `NOTES/namespace-resolution.md`, and
`NOTES/migration-workspace-to-namespace.md`. They explain the design history;
this README is the canonical operator guide. A future hard cut master will remove
the compatibility surfaces after the migration window.

## MCP Server

```bash
sm mcp
```

"#;

const README_FOOTER: &str = r#"## Development

```bash
just check
just build
just test
```
"#;

pub fn render_server_instructions(skill: Option<&SkillConfig>, tools: &[ToolContract]) -> String {
    let mut out = String::new();
    out.push_str("session-matters controls local Helioy agent sessions through smd.\n\n");
    out.push_str("Use session_run to spawn a session, session_list to inspect sessions, ");
    out.push_str(
        "session_get before acting on one id, and session_delete to terminate a session.\n\n",
    );
    append_tool_bullets(&mut out, tools);
    if let Some(skill) = skill {
        out.push('\n');
        out.push_str(skill.workflow.trim());
    }
    out
}

pub fn render_generated_instructions_rs(instructions: &str) -> String {
    format!(
        "// AUTO-GENERATED by build.rs from tools.toml - do not edit\n\
         #![allow(clippy::all)]\n\n\
         pub const SERVER_INSTRUCTIONS: &str = {instructions:?};\n"
    )
}

pub fn render_skill_md(skill: Option<&SkillConfig>, tools: &[ToolContract]) -> String {
    let mut out = String::new();
    out.push_str("---\n");
    out.push_str("name: session-matters\n");
    out.push_str("description: Control local Helioy agent sessions through smd via MCP tools.\n");
    out.push_str("---\n\n");
    out.push_str("# session-matters\n\n");
    out.push_str("Use this skill when you need to spawn, list, inspect, or terminate local Helioy agent sessions.\n\n");
    append_tool_table(&mut out, tools);
    append_examples(&mut out);
    if let Some(skill) = skill {
        out.push('\n');
        out.push_str(skill.workflow.trim());
        out.push('\n');
    }
    out
}

pub fn render_readme_md(skill: Option<&SkillConfig>, tools: &[ToolContract]) -> String {
    let mut out = String::new();
    out.push_str(README_PREAMBLE);
    append_tool_table(&mut out, tools);
    append_examples(&mut out);
    if let Some(skill) = skill {
        out.push_str("\n## Workflow\n\n");
        out.push_str(skill.workflow.trim());
        out.push('\n');
    }
    out.push_str(README_FOOTER);
    out
}

fn append_tool_bullets(out: &mut String, tools: &[ToolContract]) {
    out.push_str("Tools:\n");
    for tool in tools {
        let _ = writeln!(out, "- {}: {}", tool.name, tool.mcp_description);
    }
}

fn append_tool_table(out: &mut String, tools: &[ToolContract]) {
    out.push_str("## MCP Tools\n\n");
    out.push_str("| Tool | CLI | Purpose |\n");
    out.push_str("|------|-----|---------|\n");
    for tool in tools {
        let _ = writeln!(
            out,
            "| `{}` | `sm {}` | {} |",
            tool.name, tool.cli.name, tool.mcp_description
        );
    }
}

fn append_examples(out: &mut String) {
    out.push_str("\n## Examples\n\n");
    for example in tool_examples::examples() {
        let rendered =
            serde_json::to_string_pretty(&example.arguments).expect("example arguments serialize");
        let _ = writeln!(
            out,
            "### `{}`\n\n```json\n{}\n```\n",
            example.tool, rendered
        );
    }
}
