// AUTO-GENERATED by build.rs from tools/*.toml - do not edit
#![allow(clippy::all)]
#[rustfmt::skip]
pub const SESSION_RUN_ABOUT: &str = "Imperatively run a session through the session-matters daemon.";
#[rustfmt::skip]
pub const SESSION_RUN_RUNTIME_HELP: &str = "Runtime to launch.";
#[rustfmt::skip]
pub const SESSION_RUN_ROLE_HELP: &str = "Role label recorded on the session.";
#[rustfmt::skip]
pub const SESSION_RUN_DIR_HELP: &str = "Filesystem directory used as the runtime's working directory. Relative paths resolve against the current shell cwd; the path must exist.";
#[rustfmt::skip]
pub const SESSION_RUN_NAMESPACE_HELP: &str = "Namespace slug for the session. Overrides SM_NAMESPACE and the user namespace context.";
#[rustfmt::skip]
pub const SESSION_RUN_LABELS_HELP: &str = "Session label as key=value.";
#[rustfmt::skip]
pub const SESSION_RUN_AGENT_CONFIG_HELP: &str = "Agent config name resolved as `~/.agm/<name>/agent.toml`, or an explicit `agent.toml` path. TOML keys: `claude_config_dir` (string), `[env]` (table of strings).";
#[rustfmt::skip]
pub const SESSION_RUN_ISOLATION_HELP: &str = "Runtime isolation policy. Accepted shapes are host, docker, or docker:PROFILE.";
#[rustfmt::skip]
pub const SESSION_RUN_IMAGE_HELP: &str = "Container image for docker isolated runtimes.";
#[rustfmt::skip]
pub const SESSION_RUN_MOUNTS_HELP: &str = "Docker-only bind mount as HOST:CONTAINER[:ro|:rw]. Repeat to provide multiple mounts. Missing mode defaults to ro.";
#[rustfmt::skip]
pub const SESSION_RUN_TARGET_HELP: &str = "Runtime target. Use headless or tmux:SESSION:WINDOW.PANE. Defaults to headless.";
#[rustfmt::skip]
pub const SESSION_RUN_FORCE_HELP: &str = "Preempt an occupied tmux pane. Other spawn conflicts remain fatal.";

#[rustfmt::skip]
pub const SESSION_LIST_ABOUT: &str = "List session records, or get one session record by id.";
#[rustfmt::skip]
pub const SESSION_LIST_ID_HELP: &str = "Optional session id to load instead of listing.";
#[rustfmt::skip]
pub const SESSION_LIST_SELECTOR_HELP: &str = "Optional session selector used for matching sessions.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const SESSION_LIST_SHOW_LABELS_HELP: &str = "Render session labels in human output. JSON output already includes labels.";

#[rustfmt::skip]
pub const NAMESPACE_LIST_ABOUT: &str = "List namespace records, or get one namespace record by slug.";
#[rustfmt::skip]
pub const NAMESPACE_LIST_SLUG_HELP: &str = "Optional namespace slug to load instead of listing.";

#[rustfmt::skip]
pub const SESSION_CAPTURE_ABOUT: &str = "Capture tmux pane scrollback for one selected session.";
#[rustfmt::skip]
pub const SESSION_CAPTURE_ID_HELP: &str = "Exact session id to capture.";
#[rustfmt::skip]
pub const SESSION_CAPTURE_SCROLLBACK_LINES_HELP: &str = "Maximum tmux scrollback lines to include. When omitted, runtime-matters uses its default capture depth.";
#[rustfmt::skip]
pub const SESSION_CAPTURE_JSON_HELP: &str = "Render the captured session and capture result as JSON.";

#[rustfmt::skip]
pub const SESSION_DELETE_ABOUT: &str = "Terminate daemon owned sessions by selector.";
#[rustfmt::skip]
pub const SESSION_DELETE_SELECTOR_HELP: &str = "Session selector used for matching sessions to terminate.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const SESSION_DELETE_SIGNAL_HELP: &str = "Signal to send. Defaults to SIGTERM.";
#[rustfmt::skip]
pub const SESSION_DELETE_GRACE_SECS_HELP: &str = "Seconds to wait before SIGKILL. Defaults to 5.";

#[rustfmt::skip]
pub const SESSION_LABEL_ABOUT: &str = "Add or remove labels on selected sessions.";
#[rustfmt::skip]
pub const SESSION_LABEL_SELECTOR_HELP: &str = "Session selector used for matching sessions to label.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const SESSION_LABEL_MUTATION_HELP: &str = "Label mutation as key=value or key-.";

#[rustfmt::skip]
pub const MAIL_SEND_ABOUT: &str = "Send durable mail to selected sessions.";
#[rustfmt::skip]
pub const MAIL_SEND_TO_HELP: &str = "Recipient selector used for matching sessions.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const MAIL_SEND_FROM_HELP: &str = "Sender session id. Defaults to HELIOY_SESSION_ID when set.";
#[rustfmt::skip]
pub const MAIL_SEND_CONTENT_HELP: &str = "Message content.";

#[rustfmt::skip]
pub const MAIL_READ_ABOUT: &str = "Read unread mail for selected sessions.";
#[rustfmt::skip]
pub const MAIL_READ_SELECTOR_HELP: &str = "Inbox owner selector used for matching sessions.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const MAIL_READ_PEEK_HELP: &str = "Return unread mail without marking it read.";

#[rustfmt::skip]
pub const MAIL_CHECK_ABOUT: &str = "Return unread mail count for selected sessions.";
#[rustfmt::skip]
pub const MAIL_CHECK_SELECTOR_HELP: &str = "Inbox owner selector used for matching sessions.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";

#[rustfmt::skip]
pub const MAIL_STOP_CHECK_ABOUT: &str = "Check unread mail for stop-hook decisions.";
#[rustfmt::skip]
pub const MAIL_STOP_CHECK_SELECTOR_HELP: &str = "Inbox owner selector used for matching sessions.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";

#[rustfmt::skip]
pub const NUDGE_ABOUT: &str = "Send an ephemeral nudge to selected sessions.";
#[rustfmt::skip]
pub const NUDGE_TO_HELP: &str = "Recipient selector used for matching sessions.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const NUDGE_CONTENT_HELP: &str = "Nudge content.";

#[rustfmt::skip]
pub const LOGS_ABOUT: &str = "Read linked transcript logs for one session.";
#[rustfmt::skip]
pub const LOGS_SELECTOR_HELP: &str = "Selector that must match exactly one session with transcript logs.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const LOGS_FOLLOW_HELP: &str = "Follow appended transcript bytes.";
#[rustfmt::skip]
pub const LOGS_MAX_BYTES_HELP: &str = "Maximum bytes to return from the end of the transcript.";

#[rustfmt::skip]
pub const WAIT_ABOUT: &str = "Wait until a selector satisfies a condition.";
#[rustfmt::skip]
pub const WAIT_SELECTOR_HELP: &str = "Session selector used for matching sessions to observe.\n\nGrammar:\n  all\n  <uuid>\n  id:<uuid>\n  role:<name>\n  namespace:<slug>\n  dir:<path>\n  label:<key>=<value>\n  label:<key> in (v1, v2)\nExamples:\n  all\n  019e44f9-...\n  role:engineer\n  namespace:default\n  dir:/tmp/project\n  label:app=nginx\n  \"label:app in (web, api)\"";
#[rustfmt::skip]
pub const WAIT_FOR_HELP: &str = "Condition to wait for: running, terminated, or count=N.";
#[rustfmt::skip]
pub const WAIT_TIMEOUT_SECS_HELP: &str = "Seconds to wait before timing out. Defaults to 30.";

#[rustfmt::skip]
pub const DOCTOR_ABOUT: &str = "Report session-matters daemon health.";
